### ISSUE TITLE
Could you explain further the "Stop at ease"?

### ISSUE THREAD

**Issue by rafaeleyng** [hgiesel/anki_straight_reward#14]
Hi there

I've been trying to improve my understanding of Anki, and a question arose about the Straight Reward extension.

Anki's documentation (https://docs.ankiweb.net/#/deck-options) about the Starting Ease for new cards states (the highlight is mine):
> Starting ease controls the easiness that cards start out with. It is set when a card graduates from learning for the first time. It defaults to 250%, meaning that once you’ve finished learning a card, answering “Good” on subsequent reviews will increase the delay by approximately 2.5x (eg if the last delay was 10 days, the next delay would be 25 days). Based upon how you rate the card in subsequent reviews, **the easiness may increase** or decrease from what it starts out as.

While Straight Reward doc states:
> Stop at ease: Only cards with an ease factor between (inclusive) "Start Ease" and "Stop Ease" are considered for ease rewards

So, if I understand correctly:
1. any new card will start with 250% of ease (Anki's default value)
2. if I only ever have successes with that card, this will never drop below 250%, and will actually increase
3. if I use Straight Reward with its default ease for "Stop at ease" of 250%, it will never apply to cards that I always have success (because none of them will ever be below 250%)

If my understanding is correct, then I don't get what is the use for Straight Reward, since it will never actually apply for cards that I have success on (at least with the default values for "Starting ease" on native Anki config and "Stop Ease" on Straight Reward config). It would only apply for cards that I actually started by getting wrong (and then its ease would have dropped below 250%), and will work only until I get the ease back to 250%.

So I assume my understanding is wrong, and some clarification would be awesome.

Thanks!

**Comment by hgiesel** [comment]
A card will, by default, start with a starting ease of 250%, yes.
Now during review, the choice of answer will have the following effects:

* Again: Decrease by 15%
* Hard: Decrease by 15%
* Good: No effect on ease.
* Easy: Increase by 15%

Now the issue arises, if you have trouble remembering a card, and its ease falls way down. Unless you don't intentionally remember that "this is the card I forgot", and click "Easy" on it, it will never rise again, no matter how many you click Good. It will basically be stalled from ever getting high intervals, and you will see this card way too often. Making Anki less efficient. This is what is called "Ease Hell". For another take on it, you can watch [this video by Anking](https://www.youtube.com/watch?v=roR8S9zjUh8).

**Comment by rafaeleyng** [comment]
Thanks for the quick response! I actually watched that video before asking this question.

Still, I don't fully understand the "straight reward" concept. It is intentionally designed to (with its default values) only apply to cards that I've previously got wrong (and then dropped its ease)?

Because the README seems that it is aimed to apply to the opposite case (cards that I never get wrong, ,and that I actually get consistently correct, and than can be shown at always increasing intervals):
> Once you exceed a specific amount of successes, it is considered a "straight success". In such a case, Straight Reward will raise the ease of the cards.

As I currently understand it, the effect described in the above quotation would only be obtained if I set the "Stop at ease" to a number greater than 250%. Is this correct?

**Comment by hgiesel** [comment]
The README is intended to be written in a general tone first and foremost. It is kind of the concept of Ease in general: how should ease work in the first place?

1. The problem

From Anki default settings, the idea seems to be: the ease is supposed to be a general indicator of how hard a card is. The task of making Anki understand whether a card is hard or easy mostly falls to the user: Besides forgetting, the user has to use Hard and Easy to adjust the Ease.

However this is not an easy task. The naive user will always think: "Well, I certainly want to make sure I'll remember it". So he will opt for Hard, even if the card might not have been that hard. Problem number 1. This problem can be solved by simply educating the user not to abuse Hard, and only use it in exceptional cases.

Also generally, the user doesn't see the ease of the card. So the user has to _kinda guess, which interval seems right_, and has no way to _nudge a card back to its default ease_. However inspecting the ease of cards is just terribly annoying, and gives a big overhead while overviewing. Problem number 2.

For problem number 3, I will quote [SuperMemo](https://supermemo.guru/wiki/Algorithm_SM-18)
> We have clear evidence of dramatic changes in item difficulty in the course of learning. Those changes can be explained by anchoring, when new mnemonic context converts a difficult item into an easy item literally overnight. Anchoring can occur without any changes to the contents of the item. Naturally, due to interference, the reverse process may also occur (i.e. items may suddenly become difficult).

2. The solution

So it seems like this whole process is inherently flawed. And I'm not the first one to notice it. The [Low-key Anki approach by AJATT](https://massimmersionapproach.com/table-of-contents/anki/low-key-anki/low-key-anki-summary-and-installation/) is an alternative solution to this issue. Rather than trying to adapt the ease problem, It completely eliminates the concept of ease from the Anki algorithm.

You could say, Straight Reward is a by far less invasive approach to this issue. If Low-Key Anki eliminates all three of these issues, then Straight Award just aims at problem number two: A punishment in ease is no more that formidable, as there's a natural way to _recover_ ease now. Because of this, rating cards Hard is now more of an option than before, while it still shouldn't be abused by the user. 

3. The implementation

Straight Reward lets you make a lot of decisions, kinda like Anki itself. I hold this to be an asset of Anki: Lots of options gives power to the user.

Some of these options seem rather superfluous, I agree (e.g. the start ease).
The default settings hint at the idea, that the Straight Reward is supposed to recover the ease of cards, that you failed, or rated Hard before. For this, the user should certainly set base and step ease themselves: I have no clue, and no research to back up, what seems like a good idea.

Making stop ease settable is a good idea: Anki itself doesn't dictate what the starting ease is supposed to be. However there are other scenarios where you might set stop ease: You could have cards start at ease 225, and set the stop ease 275. This way, cards you consistently rate Good will slowly gain ease. If this is a good idea, again, I don't know.

4. The summary

> As I currently understand it, the effect described in the above quotation would only be obtained if I set the "Stop at ease" to a number greater than 250%. Is this correct?
Yes.

**Comment by rafaeleyng** [comment]
Very enlightening explanation, thank you very much 🤗 

Closing since I don't have further questions.
